USE ASSET_MANAGEMENT; 

DROP PROCEDURE IF EXISTS VIEW_ASSET_TYPES;
DROP PROCEDURE IF EXISTS INSERT_ASSET_TYPE;
DROP PROCEDURE IF EXISTS DELETE_ASSET_TYPE; 


DELIMITER &&

CREATE PROCEDURE VIEW_ASSET_TYPES()
BEGIN
	
    SELECT 
		*
	FROM
		ASSET_TYPE; 
        
END &&

DELIMITER ;

DELIMITER &&

CREATE PROCEDURE INSERT_ASSET_TYPE(IN VAR_ASSET_DESCRIPTION VARCHAR(50), IN VAR_PLAQUE BOOLEAN, IN VAR_SERIAL BOOLEAN, IN VAR_LOCATION BOOLEAN, IN VAR_BRAND BOOLEAN)
BEGIN
	
    INSERT INTO ASSET_TYPE (
		ASSET_TYPE_DESCRIPTION,
        PLAQUE_REQUIRED,
        SERIAL_REQUIRED,
        LOCATION_REQUIRED,
        BRAND_REQUIRED
    ) VALUES (
		VAR_ASSET_DESCRIPTION, 
        VAR_PLAQUE, 
        VAR_SERIAL,
        VAR_LOCATION, 
        VAR_BRAND
    ); 
        
END &&

DELIMITER ;

DELIMITER &&

CREATE PROCEDURE DELETE_ASSET_TYPE(IN VAR_ASSET_ID INT)
BEGIN

	DELETE FROM ASSET_TYPE WHERE ASSET_TYPE_ID = VAR_ASSET_ID; 

END &&

DELIMITER ; 

CALL DELETE_ASSET_TYPE(1); 