CREATE OR REPLACE PROCEDURE VALIDATE_USER(
    IN_EMAIL    IN  VARCHAR2,
    IN_PASSWORD IN  VARCHAR2,
    OUT_NOMBRE  OUT VARCHAR2,
    OUT_EMAIL   OUT VARCHAR2,
    OUT_ROLE    OUT VACHAR2    
) AS
    BEGIN 
        SELECT 
            U.NOMBRE,
            U.CORREO,
            UR.NOMBRE_ROLE 
        INTO
            OUT_NOMBRE,
            OUT_EMAIL,
            OUT_ROLE
        FROM USUARIO U
        INNER JOIN USUARIO_ROLE UR ON UR.ID_ROLE = U.ID_ROLE    
        WHERE U.CORREO = IN_EMAIL AND U.CONTRASEÑA = IN_PASSWORD;    
    
    END;


SELECT * FROM USUARIO;