SET SERVEROUTPUT ON; 

CREATE OR REPLACE PROCEDURE VALIDATE_USER(
    IN_EMAIL    IN  VARCHAR2,
    IN_PASSWORD IN  VARCHAR2,
    OUT_NOMBRE  OUT VARCHAR2,
    OUT_EMAIL   OUT VARCHAR2,
    OUT_ROLE    OUT VARCHAR2    
) AS
    BEGIN 
        SELECT 
            U.NOMBRE,
            U.CORREO,
            UR.NOMBRE_ROLE 
        INTO
            OUT_NOMBRE,
            OUT_EMAIL,
            OUT_ROLE
        FROM USUARIO U
        INNER JOIN USUARIO_ROLE UR ON UR.ID_ROLE = U.ID_ROLE    
        WHERE U.CORREO = IN_EMAIL AND U.USER_PASSWORD = IN_PASSWORD;    
    
    END;


SELECT * FROM USUARIO;

DECLARE
    VAR_NOMBRE  VARCHAR2(50);
    VAR_EMAIL   VARCHAR2(50);
    VAR_ROLE    VARCHAR2(50);
BEGIN
    VALIDATE_USER('cmorale@asset_management.com','Cris123@',VAR_NOMBRE,VAR_EMAIL,VAR_ROLE);
    DBMS_OUTPUT.PUT_LINE(VAR_NOMBRE || ' ' || VAR_EMAIL || ' ' || VAR_ROLE);
END;

SELECT * FROM USUARIO;

SELECT * FROM USUARIO_ROLE;

SELECT * FROM ACTIVOS;