SET SERVEROUTPUT ON;

CREATE OR REPLACE VIEW ACCOUNTS_RESUME AS
    SELECT 
        ID_CUENTA,
        DESCRIPCION_CUENTA    
    FROM CUENTA_CONTABLE
    ORDER BY ID_CUENTA ASC;
    
CREATE OR REPLACE VIEW ACCOUNTS_BALANCE_RESUME AS
    SELECT 
        CC.ID_CUENTA,
        CC.DESCRIPCION_CUENTA,
        CC.NATURALEZA,
        CAT.DESCRIPCION_CATEGORIA,
        CC.TOTAL_DEBITOS,
        CC.TOTAL_CREDITOS,
        CC.BALANCE
    FROM CUENTA_CONTABLE CC
    INNER JOIN CATEGORIA_CUENTA CAT ON CAT.ID_CATEGORIA = CC.ID_CATEGORIA
    ORDER BY CC.ID_CATEGORIA;

CREATE OR REPLACE PROCEDURE CREATE_ACCOUNT (
    IN_ACCOUNT              IN CUENTA_CONTABLE.ID_CUENTA%TYPE,
    IN_ACCOUNT_DESCRIPTION  IN CUENTA_CONTABLE.DESCRIPCION_CUENTA%TYPE,
    IN_ACCOUNT_CATEGORY     IN CUENTA_CONTABLE.ID_CATEGORIA%TYPE,
    IN_ACCOUNT_NATURE       IN CUENTA_CONTABLE.NATURALEZA%TYPE,
    OUT_RESULT              OUT VARCHAR
)
AS
    VAR_FIRST_CARACTER      VARCHAR2(1);
    VAR_SIMILAR_ACCOUNTS    NUMBER(10,2);
    VAR_ERROR_TRACKER       VARCHAR(255);
BEGIN

    -- Validate that the account ID match with the account category
    VAR_FIRST_CARACTER := SUBSTR(IN_ACCOUNT,1,1);
    
    IF VAR_FIRST_CARACTER != IN_ACCOUNT_CATEGORY THEN
        VAR_ERROR_TRACKER := 'Error: Account does not match with the selected category';
    END IF;
    
    --Validate if the account already exists
    SELECT COUNT(*) INTO VAR_SIMILAR_ACCOUNTS FROM CUENTA_CONTABLE WHERE ID_CUENTA = IN_ACCOUNT;
    
    IF VAR_SIMILAR_ACCOUNTS > 0 THEN 
        VAR_ERROR_TRACKER := 'Error: The account already exists, select another account number';
    END IF;
    
    
    -- Define the final return from the procedure
    IF LENGTH(VAR_ERROR_TRACKER) > 0 THEN
        OUT_RESULT := VAR_ERROR_TRACKER;
    ELSE
        OUT_RESULT := 'Successull';
    END IF;    
    
END;

DECLARE
    VAR_OUTPUT  VARCHAR(255);
BEGIN
    CREATE_ACCOUNT('1-2-2-167401','Activo Fijo - Escritorios',1,'D',VAR_OUTPUT);
    DBMS_OUTPUT.PUT_LINE(VAR_OUTPUT);
END;
