SET SERVEROUTPUT ON;

CREATE OR REPLACE VIEW VALIDACIONES_RESUME AS
    SELECT 
        V.ID_TIPO_VALIDACION,
        V.ID_CLASE,
        V.DESCRIPCION_VALIDACION,
        C.DESCRIPCION_CLASE
    FROM TIPO_VALIDACION V
    INNER JOIN CLASE C ON C.ID_CLASE = V.ID_CLASE;
    
SELECT * FROM VALIDACIONES_RESUME;

CREATE OR REPLACE PACKAGE PK_CLASSES_VALIDATIONS
IS
    PROCEDURE CREATE_CLASS_VALIDATION(
        IN_CLASS_ID                     IN CLASE.ID_CLASE%TYPE,
        IN_VALIDATION_DESCRIPTION       IN TIPO_VALIDACION.DESCRIPCION_VALIDACION%TYPE,
        OUT_RESULT                      OUT VARCHAR
    );
END;

CREATE OR REPLACE PACKAGE BODY PK_CLASSES_VALIDATIONS
IS
    ------------ Procedure to create a new validation ------------ 
    PROCEDURE CREATE_CLASS_VALIDATION(
        IN_CLASS_ID                 IN CLASE.ID_CLASE%TYPE,
        IN_VALIDATION_DESCRIPTION   IN TIPO_VALIDACION.DESCRIPCION_VALIDACION%TYPE,
        OUT_RESULT                  OUT VARCHAR
    )
    AS
        VAR_RESULT  VARCHAR(255);
        VAR_SIMILAR_VALIDATIONS NUMBER(10,2);
    BEGIN
    
        SELECT 
            COUNT(*) 
        INTO 
            VAR_SIMILAR_VALIDATIONS 
        FROM TIPO_VALIDACION 
        WHERE ID_CLASE = IN_CLASS_ID AND DESCRIPCION_VALIDACION = IN_VALIDATION_DESCRIPTION;
        
        IF VAR_SIMILAR_VALIDATIONS > 0 THEN
            VAR_RESULT := 'Error: The validation for the selected class already exists';
        END IF;
        
        IF LENGTH(VAR_RESULT) > 0 THEN
            OUT_RESULT := VAR_RESULT;
        ELSE
            OUT_RESULT := 'Successful';
            INSERT INTO TIPO_VALIDACION (ID_CLASE,DESCRIPCION_VALIDACION) VALUES (IN_CLASS_ID,IN_VALIDATION_DESCRIPTION);
        END IF;    
         
    END;

END;

DECLARE
    VAR_RESULTADO VARCHAR(255);
BEGIN
    PK_CLASSES_VALIDATIONS.CREATE_CLASS_VALIDATION(1,'Placa Vehiculo',VAR_RESULTADO);
    DBMS_OUTPUT.PUT_LINE(VAR_RESULTADO);
END;

SELECT * FROM TIPO_VALIDACION;


COMMIT;













