<?php
    include_once 'components/navigation.php';
    include_once '../controller/controller_activo.php'
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Journal Detail</title>
    <link rel="icon" href="../custom components/img/web_icon.png">
    <link href="../vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="../custom components/css/side-bar.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>


</head>

<style>
.separator {
    padding: 15px;
}

.input_separator {
    width: 50%;
}
</style>

<body class="sb-nav-fixed">

    <?php printNavigationPanel() ?>

    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid px-4">

                <h1 class="mt-4">Accounting</h1>
                <h4 class="text-muted">Depreciation</h4>

                <div class="container separator">
                    <div class="row text-left">

                        <p class="text-muted">
                            Execute the depreciation following the company and country regulations, take into
                            consideration that the depreciation journal could not be reversed and will affect all the
                            journals related to the selected class. Please complete all the information to execute the
                            depreciation:
                        </p>

                        <br><br>

                        <div class="row text-left offset-md-3">

                            <label for="txtDepreciationDescription" class='text-muted'>Depreciation Description</label>
                            <input type="text" name="txtDepreciationDescription" id="txtDepreciationDescription"
                                placeholder='Indicate the Journal Description' class="form-control input_separator">

                            <br><br><br>

                            <label for="selAssetClass" class='text-muted'>Class to be depreciated</label>
                            <select name="selAssetClass" id="selAssetClass" class="form-control input_separator">
                                <!-- Informatoin generated by JS -->
                            </select>

                            <div class="justify-content-center align-items-center">
                                <button class='btn btn-primary ' style='margin-top: 25px;' onclick='submitLine()'><i
                                        class="fa-regular fa-paper-plane"></i> Execute Depreciation</button>
                            </div>

                        </div>

                    </div>
                </div>

                <div class="container" style="display:none">
                    <div class="row">

                        <div class="col-12">

                            <table>
                                <td>
                                    <button class="btn btn-outline-primary"
                                        onclick="exportJournalsExcel('journalsResume','journals-resume')"><i
                                            class="fa-regular fa-file-excel"></i> Export Excel</button>
                                </td>
                            </table>


                        </div>
                        <br><br>
                        <div class="col-12">

                            <table class="table table-striped" id='journalsResume' name='journalsResume'>
                                <thead class="text-center table-striped thead-dark">
                                    <th>Asset Description</th>
                                    <th>Acquisition Value</th>
                                    <th>Acquisition Date</th>
                                    <th>Depreciated Periods</th>
                                    <th>Class Description</th>
                                    <th>Useful Life</th>
                                    <th>Montly Depreciation</th>
                                    <th>Accumulated Depreciation</th>
                                </thead>
                                <tbody id="tableJournalResume" name="tableJournalResume">
                                </tbody>
                            </table>


                        </div>
                    </div>
                </div>



            </div>
    </div>

    <!-- External vendor JS codes -->
    <script src="../vendor/jquery/jquery.min.js"></script>
    <script src="../vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="../vendor/chartJS/charts.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>

    <!-- Custom JS codes -->
    <script src="../custom components/js/side-bar.js"></script>
    <script src="../custom components/js/js_accounting_depreciation.js"></script>

</body>



</html>